
CREATE SCHEMA IF NOT EXISTS `neoposdb` DEFAULT CHARACTER SET utf8 ;
USE `neoposdb` ;

-- -----------------------------------------------------
-- Table `neoposdb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neoposdb`.`carrito` (
  `idcarrito` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `cost` FLOAT NULL DEFAULT NULL,
  `payment` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idcarrito`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neoposdb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neoposdb`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `cuit` INT(10) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `avatar` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neoposdb`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neoposdb`.`shop` (
  `idshop` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idshop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neoposdb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neoposdb`.`products` (
  `idproducts` INT(11) NOT NULL AUTO_INCREMENT,
  `img` VARCHAR(400) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `brand` VARCHAR(100) NULL DEFAULT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `shop_idshop` INT NOT NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neoposdb`.`carrito_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neoposdb`.`carrito_productos` (
  `idcarrito_productos` INT(11) NOT NULL AUTO_INCREMENT,
  `carrito_idcarrito` INT(11) NOT NULL,
  `products_idproducts` INT(11) NOT NULL,
  PRIMARY KEY (`idcarrito_productos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neoposdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neoposdb`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `avatar` VARCHAR(200) NULL DEFAULT NULL,
  `carrito_idcarrito` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/248x240.bmp/cc0000/ffffff', 2610, 'Acclaim', 'target customized relationships', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/219x221.jpg/ff4444/ffffff', 3409, 'Rio', 'scale visionary web services', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/220x250.jpg/cc0000/ffffff', 4428, 'Camry', 'evolve distributed e-commerce', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/250x238.png/5fa2dd/ffffff', 4585, '9000', 'evolve integrated networks', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/223x244.png/ff4444/ffffff', 3418, 'H3', 'disintermediate customized bandwidth', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/245x213.png/cc0000/ffffff', 4622, 'Alcyone SVX', 'synergize dot-com experiences', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/241x200.bmp/dddddd/000000', 4782, 'LS', 'syndicate turn-key communities', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/249x237.bmp/5fa2dd/ffffff', 4408, 'Explorer Sport', 'embrace innovative e-business', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/234x247.bmp/cc0000/ffffff', 1574, 'Camaro', 'embrace strategic schemas', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/238x217.jpg/cc0000/ffffff', 4153, 'W201', 'exploit seamless initiatives', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/236x211.bmp/5fa2dd/ffffff', 2088, 'S40', 'mesh seamless niches', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x204.png/cc0000/ffffff', 3502, 'Aviator', 'embrace revolutionary systems', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/200x237.jpg/dddddd/000000', 4158, 'Stratus', 'disintermediate collaborative networks', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/245x209.jpg/5fa2dd/ffffff', 9, 'GranSport', 'incubate viral initiatives', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/210x226.jpg/cc0000/ffffff', 632, 'RX', 'utilize value-added action-items', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/234x226.bmp/cc0000/ffffff', 4872, 'Mighty Max', 'scale global solutions', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/203x229.png/ff4444/ffffff', 3733, 'A8', 'e-enable granular networks', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/234x209.bmp/cc0000/ffffff', 4035, 'Hombre', 'iterate efficient e-markets', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/200x237.png/cc0000/ffffff', 2119, '98', 'leverage e-business markets', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/231x202.bmp/dddddd/000000', 4881, 'Forte', 'expedite out-of-the-box web services', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/216x221.bmp/5fa2dd/ffffff', 3739, 'C8 Double 12 S', 'deliver virtual web-readiness', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/231x202.bmp/cc0000/ffffff', 1634, 'Prizm', 'transform efficient paradigms', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/220x244.bmp/cc0000/ffffff', 4264, 'S-Type', 'grow intuitive relationships', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/206x204.bmp/cc0000/ffffff', 2342, 'QX', 'aggregate scalable schemas', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/209x227.png/cc0000/ffffff', 1500, 'Ranger', 'productize strategic interfaces', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/207x218.bmp/dddddd/000000', 2510, 'S8', 'enhance 24/7 vortals', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/222x245.png/dddddd/000000', 3060, 'S40', 'embrace plug-and-play users', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/250x246.png/ff4444/ffffff', 963, 'Jetta', 'revolutionize dot-com eyeballs', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/207x209.jpg/5fa2dd/ffffff', 2614, 'F250', 'harness mission-critical e-markets', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/231x202.bmp/dddddd/000000', 2962, 'Yukon', 'exploit next-generation paradigms', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/237x208.bmp/cc0000/ffffff', 3246, 'Metro', 'matrix bricks-and-clicks e-business', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/232x226.bmp/dddddd/000000', 4898, 'Park Avenue', 'benchmark next-generation methodologies', 'Fusce consequat. Nulla nisl. Nunc nisl.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x227.bmp/5fa2dd/ffffff', 3423, 'Ram 3500', 'incentivize best-of-breed content', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/234x203.png/dddddd/000000', 1282, 'Cavalier', 'maximize collaborative metrics', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/201x243.png/dddddd/000000', 4453, '4Runner', 'engage interactive methodologies', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/201x239.jpg/dddddd/000000', 392, '2500', 'disintermediate frictionless initiatives', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/211x215.jpg/dddddd/000000', 2234, 'Frontier', 'utilize leading-edge functionalities', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x238.jpg/ff4444/ffffff', 689, 'Silverado 2500', 'unleash innovative niches', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/207x222.jpg/5fa2dd/ffffff', 2648, 'Azera', 'integrate back-end paradigms', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x212.jpg/5fa2dd/ffffff', 3412, 'Frontier', 'monetize B2B deliverables', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x237.png/ff4444/ffffff', 35, '900', 'integrate global metrics', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/216x212.bmp/cc0000/ffffff', 3054, 'Quattroporte', 'drive killer solutions', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/210x247.bmp/cc0000/ffffff', 603, '1500', 'synthesize transparent initiatives', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/231x244.png/ff4444/ffffff', 3603, 'Corvette', 'enable seamless applications', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/232x204.png/dddddd/000000', 4437, 'M5', 'revolutionize holistic niches', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/204x244.bmp/dddddd/000000', 268, 'Aspen', 'implement efficient web-readiness', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/216x206.png/ff4444/ffffff', 3323, 'Corolla', 'integrate visionary communities', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/232x234.bmp/5fa2dd/ffffff', 2051, 'MR2', 'innovate viral synergies', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/212x240.jpg/cc0000/ffffff', 3473, 'Monte Carlo', 'streamline B2B infomediaries', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/207x201.jpg/cc0000/ffffff', 4194, 'Galant', 'enable innovative initiatives', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/206x201.jpg/5fa2dd/ffffff', 20, 'Avanti', 'e-enable killer applications', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/204x219.png/5fa2dd/ffffff', 1561, 'SRX', 'unleash strategic markets', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/223x240.bmp/ff4444/ffffff', 951, 'Rodeo', 'generate leading-edge convergence', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/231x206.jpg/5fa2dd/ffffff', 1957, 'RX', 'synthesize best-of-breed synergies', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/234x212.jpg/dddddd/000000', 437, 'Dakota Club', 'enable intuitive e-markets', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/246x237.png/5fa2dd/ffffff', 3851, 'rio', 'expedite granular eyeballs', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/247x209.bmp/cc0000/ffffff', 4517, 'Eurovan', 'streamline leading-edge bandwidth', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/215x213.jpg/ff4444/ffffff', 1296, 'Suburban 2500', 'syndicate distributed e-services', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/224x215.bmp/dddddd/000000', 3774, '9-5', 'harness real-time initiatives', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x226.bmp/5fa2dd/ffffff', 4621, '300M', 'empower 24/7 partnerships', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/216x219.png/dddddd/000000', 2375, 'Esprit', 'engineer holistic convergence', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/246x239.bmp/dddddd/000000', 2729, 'Quest', 'productize strategic channels', 'Fusce consequat. Nulla nisl. Nunc nisl.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/216x200.png/cc0000/ffffff', 2526, 'Charger', 'seize customized deliverables', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/203x223.jpg/cc0000/ffffff', 4836, 'Ram 2500', 'deploy synergistic relationships', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/226x245.jpg/cc0000/ffffff', 535, 'Diablo', 'revolutionize bricks-and-clicks supply-chains', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/219x219.png/cc0000/ffffff', 2751, 'Mustang', 'visualize 24/7 infrastructures', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/214x250.png/5fa2dd/ffffff', 3006, 'Viper', 'deploy magnetic action-items', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/238x209.jpg/5fa2dd/ffffff', 2183, 'Thunderbird', 'facilitate collaborative e-commerce', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/241x222.png/5fa2dd/ffffff', 1001, 'xB', 'whiteboard integrated e-commerce', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/226x241.png/5fa2dd/ffffff', 4720, 'S70', 'generate mission-critical content', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/225x200.png/ff4444/ffffff', 3394, 'Forenza', 'engage efficient markets', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/205x228.png/5fa2dd/ffffff', 698, 'Firebird', 'monetize web-enabled functionalities', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/210x237.png/cc0000/ffffff', 3641, 'Thunderbird', 'seize robust communities', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/248x228.bmp/ff4444/ffffff', 1993, 'Intrigue', 'target dynamic markets', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/248x217.png/cc0000/ffffff', 1869, 'Cabriolet', 'integrate end-to-end mindshare', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/247x224.bmp/dddddd/000000', 2780, 'Freestar', 'redefine cross-media applications', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/239x205.png/ff4444/ffffff', 3657, 'Tahoe', 'engineer collaborative interfaces', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/206x228.jpg/5fa2dd/ffffff', 913, 'Escape', 'optimize front-end niches', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/241x208.png/ff4444/ffffff', 4966, 'Diablo', 'incubate user-centric web-readiness', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/210x219.bmp/5fa2dd/ffffff', 4429, 'F150', 'transition cutting-edge paradigms', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x202.png/ff4444/ffffff', 4489, 'Miata MX-5', 'generate out-of-the-box vortals', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/220x239.jpg/dddddd/000000', 2938, 'Expedition', 'utilize mission-critical bandwidth', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/201x229.jpg/ff4444/ffffff', 4471, '968', 'facilitate visionary markets', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/219x243.png/ff4444/ffffff', 910, 'Malibu', 'harness clicks-and-mortar models', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/226x242.png/dddddd/000000', 3114, 'Golf', 'exploit cutting-edge applications', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/234x226.jpg/5fa2dd/ffffff', 1652, 'RX', 'strategize impactful initiatives', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/246x236.png/cc0000/ffffff', 4163, 'B-Series Plus', 'implement value-added ROI', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/235x239.bmp/5fa2dd/ffffff', 2177, 'Seville', 'extend killer applications', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x217.jpg/5fa2dd/ffffff', 1022, 'Prius Plug-in', 'embrace intuitive communities', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/209x203.jpg/ff4444/ffffff', 2448, 'Sonata', 'enhance customized mindshare', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/221x234.png/cc0000/ffffff', 2749, 'Lumina', 'repurpose viral web services', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x213.png/ff4444/ffffff', 3308, 'Tacoma Xtra', 'iterate synergistic e-services', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x248.bmp/5fa2dd/ffffff', 3200, 'ZX2', 'maximize clicks-and-mortar web services', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x224.bmp/5fa2dd/ffffff', 2744, 'Sierra Hybrid', 'envisioneer ubiquitous bandwidth', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x229.jpg/dddddd/000000', 283, 'Sentra', 'optimize cutting-edge deliverables', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x226.jpg/cc0000/ffffff', 1071, 'Stealth', 'innovate dot-com e-tailers', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/250x229.jpg/5fa2dd/ffffff', 2351, '4Runner', 'monetize e-business content', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/239x240.bmp/cc0000/ffffff', 4856, 'Camaro', 'incentivize vertical schemas', 'Fusce consequat. Nulla nisl. Nunc nisl.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/200x202.bmp/cc0000/ffffff', 4186, 'X6', 'exploit magnetic paradigms', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/219x236.jpg/5fa2dd/ffffff', 3965, 'Diablo', 'whiteboard scalable action-items', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/225x224.bmp/cc0000/ffffff', 869, 'Diablo', 'evolve killer synergies', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/243x244.jpg/5fa2dd/ffffff', 37, 'Spyder', 'synthesize wireless methodologies', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/241x228.bmp/cc0000/ffffff', 2628, 'Safari', 'leverage turn-key interfaces', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/231x211.png/5fa2dd/ffffff', 1968, 'Esperante', 'evolve strategic users', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/211x244.png/5fa2dd/ffffff', 3243, 'Expedition', 'e-enable cutting-edge metrics', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/243x247.bmp/ff4444/ffffff', 2720, 'NSX', 'exploit vertical platforms', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/239x222.png/ff4444/ffffff', 1742, 'Outlander', 'redefine B2C solutions', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/207x234.bmp/cc0000/ffffff', 4233, 'Corvette', 'incentivize killer e-tailers', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/225x217.jpg/dddddd/000000', 1065, 'LS', 'redefine cross-platform content', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/228x230.png/5fa2dd/ffffff', 2383, 'Aspen', 'envisioneer magnetic web services', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/215x242.png/ff4444/ffffff', 4669, 'Legend', 'drive rich applications', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/210x211.png/dddddd/000000', 3170, 'Accent', 'revolutionize viral e-business', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/236x227.png/dddddd/000000', 4828, 'Odyssey', 'mesh end-to-end niches', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/221x232.bmp/cc0000/ffffff', 2032, 'Yukon', 'transform holistic communities', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/224x244.jpg/ff4444/ffffff', 4359, 'Diamante', 'engineer user-centric niches', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/212x236.jpg/5fa2dd/ffffff', 1647, 'Vision', 'transition revolutionary technologies', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/219x213.bmp/5fa2dd/ffffff', 4166, 'Ram Van 1500', 'cultivate clicks-and-mortar experiences', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/228x249.bmp/5fa2dd/ffffff', 873, '4Runner', 'orchestrate interactive infomediaries', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/233x208.jpg/ff4444/ffffff', 1856, 'Sierra', 'synthesize rich content', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/247x249.png/5fa2dd/ffffff', 1238, 'Skyhawk', 'morph B2B eyeballs', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x235.jpg/ff4444/ffffff', 3499, 'Savana 3500', 'benchmark seamless applications', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/203x245.png/cc0000/ffffff', 3425, 'Stealth', 'scale back-end action-items', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x238.png/cc0000/ffffff', 3880, 'Highlander', 'repurpose efficient platforms', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/207x210.bmp/5fa2dd/ffffff', 1234, 'H1', 'enhance revolutionary web-readiness', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/226x229.jpg/cc0000/ffffff', 4365, 'Aveo', 'engage 24/7 mindshare', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/238x242.bmp/dddddd/000000', 3030, 'CLK-Class', 'deliver revolutionary users', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/228x228.png/cc0000/ffffff', 2788, 'Impala', 'unleash mission-critical solutions', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/202x238.bmp/ff4444/ffffff', 2839, 'Yukon XL 1500', 'envisioneer visionary initiatives', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/216x247.bmp/cc0000/ffffff', 2881, 'Passat', 'generate sticky systems', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/240x227.png/cc0000/ffffff', 4178, 'LeSabre', 'engage magnetic partnerships', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/203x224.bmp/ff4444/ffffff', 1252, 'Firebird', 'optimize enterprise solutions', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/225x246.jpg/ff4444/ffffff', 3056, 'Cherokee', 'transition sexy convergence', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/201x236.png/ff4444/ffffff', 3689, 'Yukon', 'utilize dynamic functionalities', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/214x223.jpg/5fa2dd/ffffff', 4941, 'RX Hybrid', 'synthesize 24/365 synergies', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/238x241.jpg/cc0000/ffffff', 4636, 'Sprinter', 'incentivize revolutionary e-business', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/219x230.png/5fa2dd/ffffff', 3888, 'Caliber', 'productize wireless markets', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/238x238.jpg/5fa2dd/ffffff', 3685, 'QX', 'evolve synergistic methodologies', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/224x209.jpg/ff4444/ffffff', 516, 'Avalanche', 'reinvent synergistic initiatives', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x236.jpg/cc0000/ffffff', 286, 'F250', 'innovate back-end e-tailers', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/235x206.jpg/dddddd/000000', 3368, 'Ram 3500', 'streamline proactive relationships', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/213x224.png/dddddd/000000', 2331, 'Contour', 'envisioneer compelling supply-chains', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/237x206.bmp/ff4444/ffffff', 3575, 'Econoline E150', 'implement cross-platform metrics', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/236x232.bmp/dddddd/000000', 1298, 'SLK-Class', 'utilize out-of-the-box portals', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/237x250.png/5fa2dd/ffffff', 4250, 'Tacoma', 'e-enable frictionless niches', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/237x205.bmp/ff4444/ffffff', 1689, 'Pilot', 'brand user-centric channels', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/219x229.jpg/cc0000/ffffff', 1471, 'XLR', 'reintermediate distributed networks', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/246x218.bmp/ff4444/ffffff', 917, 'XJ', 'monetize extensible partnerships', 'Fusce consequat. Nulla nisl. Nunc nisl.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/208x246.bmp/ff4444/ffffff', 2976, 'Cirrus', 'extend impactful markets', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/231x204.bmp/cc0000/ffffff', 3395, 'XT', 'repurpose holistic ROI', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/227x203.png/dddddd/000000', 4154, 'RX-8', 'grow clicks-and-mortar users', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/248x213.jpg/5fa2dd/ffffff', 1501, 'Daewoo Kalos', 'transform value-added content', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/217x201.jpg/ff4444/ffffff', 4638, 'R8', 'exploit distributed technologies', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/223x246.jpg/dddddd/000000', 194, '600SL', 'engage leading-edge networks', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/234x242.bmp/cc0000/ffffff', 38, 'Suburban 2500', 'strategize viral deliverables', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/213x205.bmp/5fa2dd/ffffff', 2694, '3 Series', 'extend open-source e-business', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x230.bmp/dddddd/000000', 448, 'Yukon', 'engineer user-centric web services', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/250x227.jpg/ff4444/ffffff', 3778, '300SD', 'extend revolutionary web-readiness', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x210.png/cc0000/ffffff', 2080, 'Continental Super', 'generate distributed portals', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/245x243.bmp/cc0000/ffffff', 477, 'ES', 'implement B2C partnerships', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/228x214.png/dddddd/000000', 1521, 'Quest', 'synthesize plug-and-play solutions', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/239x228.jpg/dddddd/000000', 3934, 'Integra', 'envisioneer transparent interfaces', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/207x223.bmp/ff4444/ffffff', 2652, 'E-Series', 'leverage compelling networks', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/240x211.bmp/ff4444/ffffff', 4263, 'CTS', 'reintermediate one-to-one solutions', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x209.jpg/cc0000/ffffff', 3531, 'Optima', 'brand distributed metrics', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/203x201.bmp/cc0000/ffffff', 2032, 'Continental GT', 'e-enable interactive solutions', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/225x211.bmp/ff4444/ffffff', 3451, 'E-Class', 'redefine one-to-one e-business', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/214x220.jpg/cc0000/ffffff', 4481, 'Scoupe', 'embrace viral e-markets', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/211x202.jpg/ff4444/ffffff', 1949, 'MPV', 'repurpose bricks-and-clicks content', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/243x224.bmp/cc0000/ffffff', 3359, 'Ranger', 'orchestrate distributed methodologies', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x239.jpg/dddddd/000000', 2358, 'Cooper Clubman', 'streamline customized interfaces', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x238.bmp/ff4444/ffffff', 1718, 'Ram 2500', 'innovate customized metrics', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/242x232.jpg/ff4444/ffffff', 3097, 'H2', 'innovate leading-edge users', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/249x232.jpg/cc0000/ffffff', 4021, 'RAV4', 'engineer out-of-the-box supply-chains', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/244x210.png/ff4444/ffffff', 3832, 'Q', 'iterate one-to-one infomediaries', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/224x219.jpg/ff4444/ffffff', 4572, 'Summit', 'strategize e-business markets', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/248x243.bmp/ff4444/ffffff', 3696, 'Prius', 'recontextualize value-added ROI', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/208x205.bmp/ff4444/ffffff', 2085, '80', 'strategize innovative synergies', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/202x230.jpg/ff4444/ffffff', 3554, 'Corvette', 'matrix next-generation infrastructures', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/200x213.png/dddddd/000000', 3475, 'ZX2', 'recontextualize next-generation functionalities', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/226x213.jpg/dddddd/000000', 4833, '4Runner', 'redefine cross-platform action-items', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/237x250.png/5fa2dd/ffffff', 1161, 'Accent', 'strategize killer infomediaries', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/226x212.bmp/cc0000/ffffff', 877, 'Intrigue', 'orchestrate web-enabled architectures', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/241x203.jpg/dddddd/000000', 2023, 'Golf', 'enhance end-to-end infomediaries', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/215x238.jpg/cc0000/ffffff', 3597, 'Mustang', 'integrate bricks-and-clicks deliverables', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x203.jpg/cc0000/ffffff', 3802, 'Venture', 'matrix dot-com networks', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/236x200.bmp/dddddd/000000', 2077, 'SLX', 'target robust niches', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/248x244.jpg/dddddd/000000', 3145, 'LX', 'reintermediate mission-critical partnerships', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/204x215.jpg/cc0000/ffffff', 3104, 'Rio', 'engage holistic architectures', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/205x248.png/5fa2dd/ffffff', 1570, '2500 Club Coupe', 'maximize next-generation content', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/230x224.bmp/ff4444/ffffff', 915, 'Rio5', 'harness B2B infrastructures', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/229x228.jpg/5fa2dd/ffffff', 3593, 'F450', 'incubate viral bandwidth', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/240x247.png/ff4444/ffffff', 3390, 'Montero', 'streamline granular interfaces', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/245x243.bmp/5fa2dd/ffffff', 3810, 'Century', 'benchmark dynamic web-readiness', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/240x247.png/5fa2dd/ffffff', 4147, 'H3', 'incentivize customized infrastructures', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/232x223.png/5fa2dd/ffffff', 1010, 'LS', 'enable dynamic solutions', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/229x216.jpg/ff4444/ffffff', 2686, 'G-Series G20', 'visualize user-centric niches', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/245x234.bmp/dddddd/000000', 3719, 'Tacoma Xtra', 'aggregate compelling vortals', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 3);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/249x206.bmp/5fa2dd/ffffff', 4869, '1500', 'morph efficient applications', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/218x202.jpg/dddddd/000000', 2505, 'DeVille', 'transform end-to-end channels', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1);
insert into products (img, price, brand, title, description, shop_idshop) values ('http://dummyimage.com/240x208.png/dddddd/000000', 1879, 'XJ', 'reinvent visionary solutions', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 2);

